"""
暖心故事视频 — 通用构建脚本。
9:16 vertical: 1080x1920. Per-clip: numpy generates frames with right-sweep B&W→color wipe,
piped to ffmpeg → clip_N.mp4. Then xfade chain + BGM.
Subtitles are baked into the source images (generated by AI), NOT overlaid here.
ZERO ffmpeg filter expressions — all effects done in Python.

Usage:
  python build_story_video.py

Before running:
  1. Put 10 images named img_01.jpeg ~ img_10.jpeg in IMG_DIR
  2. Clear TMP_DIR
  3. Set BGM path
"""
import subprocess
import os
import numpy as np
from PIL import Image

# ============================================================
# CONFIG — adjust these per project
# ============================================================
WORKSPACE = r"E:\Users\admin\Desktop\王海鑫\Tutorial"
RUN_DIR = os.path.join(WORKSPACE, ".manify", "runs", "FIXME_run_id")
IMG_DIR = os.path.join(RUN_DIR, "imgs_v2")
TMP_DIR = os.path.join(RUN_DIR, "clips_v4")
BGM = os.path.join(RUN_DIR, "ref_bgm.mp3")
OUTPUT = os.path.join(WORKSPACE, "FIXME_output_name_final.mp4")

# ============================================================
# PARAMETERS
# ============================================================
N = 10              # number of images
CLIP_DUR = 4.5      # seconds per clip
FADE_DUR = 0.5      # crossfade duration
WIPE_START = 0.5    # when B&W→color wipe begins
WIPE_DUR = 1.5      # wipe duration
W = 1080            # output width
H = 1920            # output height
FPS = 30
NF = int(CLIP_DUR * FPS)  # 135

os.makedirs(TMP_DIR, exist_ok=True)
os.makedirs(IMG_DIR, exist_ok=True)


def make_bw(rgb):
    """Grayscale via luminosity weights, return 3-channel."""
    g = (rgb[:, :, 0] * 0.299 + rgb[:, :, 1] * 0.587 + rgb[:, :, 2] * 0.114).astype(np.uint8)
    return np.stack([g, g, g], axis=-1)


# ============================================================
# Step 1: Load & preprocess images
# ============================================================
print("Loading images...")
processed = []
for i in range(1, N + 1):
    img = Image.open(os.path.join(IMG_DIR, f"img_{i:02d}.jpeg")).convert("RGB")
    iw, ih = img.size
    target_ratio = H / W
    img_ratio = ih / iw
    if img_ratio > target_ratio:
        new_w = W
        new_h = int(W * img_ratio)
        scaled = img.resize((new_w, new_h), Image.LANCZOS)
        top = (new_h - H) // 2
        cropped = scaled.crop((0, top, W, top + H))
    else:
        new_h = H
        new_w = int(H / img_ratio)
        scaled = img.resize((new_w, new_h), Image.LANCZOS)
        left = (new_w - W) // 2
        cropped = scaled.crop((left, 0, left + W, H))
    arr = np.array(cropped)
    processed.append({"color": arr, "bw": make_bw(arr)})
    print(f"  img_{i:02d} loaded: {arr.shape}")

# ============================================================
# Step 2: Generate each clip (pipe frames to ffmpeg)
# ============================================================
print()
print("=" * 60)
print("Generating clips (subtitles baked into images)...")
print("=" * 60)

for i in range(N):
    dst = os.path.join(TMP_DIR, f"clip_{i:02d}.mp4")
    if os.path.exists(dst):
        print(f"  clip_{i:02d}.mp4 exists, skip")
        continue

    color = processed[i]["color"]
    bw = processed[i]["bw"]

    cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{W}x{H}",
        "-r", str(FPS), "-i", "-",
        "-c:v", "libx264", "-preset", "fast", "-crf", "18",
        "-pix_fmt", "yuv420p", "-an", dst
    ]

    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE,
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    for fi in range(NF):
        tl = (fi + 0.5) / FPS
        wipe = min(1.0, max(0.0, (tl - WIPE_START) / WIPE_DUR))
        xb = int(wipe * W)

        frame = bw.copy()
        if xb > 0:
            frame[:, :xb] = color[:, :xb]

        proc.stdin.write(frame.tobytes())

    proc.stdin.close()
    rc = proc.wait()
    if rc == 0 and os.path.exists(dst):
        print(f"  clip_{i:02d}.mp4 OK ({os.path.getsize(dst)/1024:.0f}KB)")
    else:
        print(f"  clip_{i:02d}.mp4 FAIL (rc={rc})")
        exit(1)

# ============================================================
# Step 3: xfade chain + BGM
# ============================================================
print()
print("=" * 60)
print("Chaining with xfade + BGM...")
print("=" * 60)

inputs = []
fc_parts = []
for j in range(N):
    inputs += ["-i", os.path.join(TMP_DIR, f"clip_{j:02d}.mp4")]
    fc_parts.append(f"[{j}:v]setpts=PTS-STARTPTS[clip{j}]")

offset = CLIP_DUR - FADE_DUR
prev = "clip0"
for j in range(1, N):
    cur_offset = offset * j
    fc_parts.append(
        f"[{prev}][clip{j}]xfade=transition=fade:duration={FADE_DUR}:offset={cur_offset}[x{j}]"
    )
    prev = f"x{j}"

inputs += ["-i", BGM]
total_dur = offset * (N - 1) + CLIP_DUR

fc_path = os.path.join(TMP_DIR, "chain.txt")
with open(fc_path, "w") as f:
    f.write(";\n".join(fc_parts))

cmd = (
    ["ffmpeg", "-y"] + inputs +
    ["-filter_complex_script", fc_path,
     "-map", f"[{prev}]", "-map", f"{N}:a",
     "-c:v", "libx264", "-preset", "fast", "-crf", "23",
     "-pix_fmt", "yuv420p",
     "-c:a", "aac", "-b:a", "192k", "-shortest",
     "-t", str(total_dur), OUTPUT]
)

print(f"  Total duration: {total_dur}s")
r = subprocess.run(cmd, capture_output=True, text=True)
if r.returncode == 0:
    sz = os.path.getsize(OUTPUT)
    print(f"  SUCCESS — {sz/1024:.0f}KB")
else:
    print("  FAILED")
    print("STDERR:", r.stderr[-2000:])
    exit(1)

print()
print("DONE:", OUTPUT)
